'use strict';

module.exports = {
  apiUrl: process.env.API_URL || 'http://localhost:3000/api/',
  graphqlUrl: process.env.GRAPHQL_URL || 'http://localhost:3000/graphql/',
  apiToken: process.env.TOKEN_JWT_WEB || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoic29saWNpdGFudGUiLCJwZXJtaXNzaW9ucyI6WyJ0cmFtaXRlczpyZWFkIiwidHJhbWl0ZXM6Y3JlYXRlIiwidHJhbWl0ZXM6dXBkYXRlIiwidHJhbWl0ZXNEb2M6cmVhZCIsInRyYW1pdGVzRG9jOmNyZWF0ZSIsInRyYW1pdGVzRG9jOnVwZGF0ZSIsInBhZ29zOnJlYWQiLCJwYWdvczpjcmVhdGUiLCJwYWdvczp1cGRhdGUiLCJzb2xpY2l0YW50ZXM6cmVhZCIsInNvbGljaXRhbnRlczpjcmVhdGUiLCJzb2xpY2l0YW50ZXM6dXBkYXRlIiwiZG9jdW1lbnRvczpyZWFkIiwicGFyYW1ldHJvczpyZWFkIiwiZGVwYXJ0YW1lbnRvczpyZWFkIiwiZGVwYXJ0YW1lbnRvczpjcmVhdGUiLCJkZXBhcnRhbWVudG9zOnVwZGF0ZSIsImRlcGFydGFtZW50b3M6ZGVsZXRlIiwicHJvdmluY2lhczpyZWFkIiwicHJvdmluY2lhczpjcmVhdGUiLCJwcm92aW5jaWFzOnVwZGF0ZSIsInByb3ZpbmNpYXM6ZGVsZXRlIiwibXVuaWNpcGlvczpyZWFkIiwibXVuaWNpcGlvczpjcmVhdGUiLCJtdW5pY2lwaW9zOnVwZGF0ZSIsIm11bmljaXBpb3M6ZGVsZXRlIiwiYXJjaGl2b3M6cmVhZCIsImFyY2hpdm9zOmNyZWF0ZSIsImFyY2hpdm9zOnVwZGF0ZSIsIm5vdGlmaWNhY2lvbmVzOnJlYWQiLCJub3RpZmljYWNpb25lczpjcmVhdGUiLCJub3RpZmljYWNpb25lczp1cGRhdGUiLCJzZWdpcDpyZWFkIl0sImlhdCI6MTUxNTcwMTk1N30.sgNYPxbOmlGJogE-7gvoulZFAcF4YzkrWs9uUpWR0pU'
};
